"""empty message

Revision ID: 37432596483b
Revises: 
Create Date: 2020-03-14 01:03:36.005325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37432596483b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_table('octogone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ranked', sa.Boolean(), nullable=False),
    sa.Column('closed_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_octogone_id'), 'octogone', ['id'], unique=False)
    op.create_table('season',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_id'), 'season', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('game_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('ranked', sa.Boolean(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_rule_id'), 'game_rule', ['id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('global_mmr', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('pussy_score', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    op.create_table('game_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('mmr', sa.Float(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_profile_id'), 'game_profile', ['id'], unique=False)
    op.create_table('game_rule_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('modification_datetime', sa.DateTime(), nullable=True),
    sa.Column('mmr', sa.Float(), nullable=False),
    sa.Column('octogone_accepted', sa.Integer(), nullable=False),
    sa.Column('octogone_refused', sa.Integer(), nullable=False),
    sa.Column('game_rule_id', sa.Integer(), nullable=False),
    sa.Column('game_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_profile_id'], ['game_profile.id'], ),
    sa.ForeignKeyConstraint(['game_rule_id'], ['game_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_rule_profile_id'), 'game_rule_profile', ['id'], unique=False)
    op.create_table('octogones_game_rule_profile_association',
    sa.Column('octogone_id', sa.Integer(), nullable=False),
    sa.Column('game_rule_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_rule_profile_id'], ['game_rule_profile.id'], ),
    sa.ForeignKeyConstraint(['octogone_id'], ['octogone.id'], ),
    sa.PrimaryKeyConstraint('octogone_id', 'game_rule_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('octogones_game_rule_profile_association')
    op.drop_index(op.f('ix_game_rule_profile_id'), table_name='game_rule_profile')
    op.drop_table('game_rule_profile')
    op.drop_index(op.f('ix_game_profile_id'), table_name='game_profile')
    op.drop_table('game_profile')
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_game_rule_id'), table_name='game_rule')
    op.drop_table('game_rule')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_season_id'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_octogone_id'), table_name='octogone')
    op.drop_table('octogone')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
